language: elixir

elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.1
otp_release:
  - '19.3'
  - '20.3'
  - '21.0'

before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - MIMX_ENV=test mix deps.get

script:
  - MIX_ENV=test mix test --trace
